services:
  ros:
    build: .                     # 同じディレクトリの Dockerfile からイメージを作る
    image: my_ros:jazzy
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ros2_ws/src:/root/ros2_ws/src   # 自分のプログラムを共有する
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    tty: true
